### ISSUE TITLE
update the readme

### ISSUE THREAD

**Issue by ArnavScripts** [ArnavScripts/oct-scripts#1]
add some basic stuff to the readme

**Comment by Pragya2056** [comment]
Please assign me. 
I will add the following things to the readme. 
1. The Guide "How to contribute"
2. Repo Status
3. Contributors image link
4. Rules to follow while contributing. 
5. The link to the code of conduct after adding the file - code of conduct
6. A humble request to star the repository.

**Comment by Pragya2056** [comment]
The PR #6
